.github/workflows/map-diff.yml

Внес улучшения в нашу систему CI/CD, добавив новый GitHub Action, который автоматически проверяет изменения в картах при создании `pull request`. Вот что было сделано:
- **Добавлен GitHub Action** для отслеживания изменений в `.yml` файлах, находящихся в папке `Resources/Maps/`. Этот Action анализирует изменения, добавления, удаления и переименования карт.
- **Создание отчета** об изменениях: При наличии изменений в картах, Action автоматически создает комментарий в pull request с указанием:
- Названия измененных, добавленных, удаленных или переименованных карт.
- Последнего пользователя, который редактировал каждую карту.
:cl: **Mathemat1ka**
- add: Новый тест GitHub Action

20.08.2024 Add new test-map-diff-check | GitHUB Action

---

build.bat
runclient-bin.bat
runserver-bin.bat

Добавлены новые шорткарты для сборки и для запуска сборки
`build.bat` - собирает сборку в указанном режиме, пример: `./build.bat Release`, если подгружены секреты, то собирает вместе с ними
`runclient-bin.bat` - запускает бинарник клиента без компиляции
`runserver-bin.bat` - запускает бинарник сервера без компиляции
**Медиа**
**Проверки**
**Изменения**

Add new bats for building and running project

---

.github/workflows/build-test-debug.yml

Make tests run for development branch

---

.github/workflows/build-map-renderer.yml
.github/workflows/test-packaging.yml
.github/workflows/validate-rgas.yml
.github/workflows/validate-rsis.yml
.github/workflows/validate_mapfiles.yml
.github/workflows/yaml-linter.yml

Make tests run for development branch v2

---

Resources/Prototypes/game_presets.yml

Добавить Greenshift в список режимов для голосования
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Добавлен Greenshift в список режимов голосования

Add greenshift to presets vote

---

Content.Shared/Projectiles/ProjectileComponent.cs
Content.Shared/Projectiles/SharedProjectileSystem.cs
Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs

Теперь возможно застрелиться.
Если нацелить оружие на самого себя, то патроны будут наносить урон вам же.
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Теперь возможно застрелиться

Теперь возможно застрелиться

---

Content.IntegrationTests/Tests/Preferences/ServerDbSqliteTests.cs

**Медиа**
**Проверки**
**Изменения**

Fix voice in server db sqlite test

---

Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs

**Медиа**
**Проверки**
**Изменения**

Fix TTS default voices

---

Resources/Prototypes/Voice/speech_emote_sounds.yml

**Медиа**
**Проверки**
**Изменения**

Fix emote sounds error with reptilian's scream

---

Resources/Prototypes/_Exodus/Body/Parts/felinid.yml
Resources/Prototypes/_Exodus/Body/Prototypes/felinid.yml
Resources/Prototypes/_Exodus/Entities/Mobs/Species/felinid.yml

**Медиа**
Была пофикшена скорость бега фелинидов, а также их метаболизм, он однозначно животный
**Проверки**
**Изменения**
:cl:
- fix: Исправлена скорость бега фелинидов и их метаболизм

Fix felinids speed and organs

---

Content.Server/Parallax/BiomeSystem.cs

Исправлена регенерация карт. Ранее, после исправления сохранения карт планет, появилась проблема, что при повторной прогрузке чанка, даже после удаления всех сущностей в нём, все эти сущности возвращались обратно. Данный PR исправляет эту проблему.
:cl:
- fix: Исправлена регенерация карт

Fix maps regeneration

---

Content.Server/NPC/Components/NPCStandsUpComponent.cs
Content.Server/NPC/HTN/PrimitiveTasks/Operators/Combat/StandUpOperator.cs
Resources/Prototypes/NPCs/Combat/melee.yml
Resources/Prototypes/NPCs/idle.yml

NPC научили вставать, в этот раз по настоящему
:cl:
- fix: NPC научились вставать

Make NPC stand up for real

---

Resources/Prototypes/game_presets.yml

Отключение космической пыли.
При низком онлайне, когда полное отсутствие инженеров это норма станция просто разваливается и чинить её некому. В добавок даже когда инженеры есть это слишком сильно мешает. Это событие подходит только если есть высокий онлайн.
:cl:
- remove: Отключена космическая пыль

Disable space dust destructing stations

---

Content.Packaging/ClientPackaging.cs
Content.Packaging/ServerPackaging.cs

Fix packaging

---

Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
Content.Server/NPC/Systems/NPCCombatSystrem.Ability.cs
Content.Shared/Actions/BaseActionComponent.cs
Content.Shared/Movement/Events/FootstepsSoundAttemtEvent.cs
Content.Shared/Movement/Systems/SharedMoverController.cs
Content.Shared/Standing/StandingStateSystem.cs

Необходимая публичная часть обновления.
**Изменения**
:cl:
- tweak: Добавлен ивент на звуки шагов
- tweak: Минорные изменения названий

Time to fly

---

Resources/Prototypes/Corvax/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/Corvax/Species/vulpkanin.yml
Resources/Prototypes/_Exodus/Entities/Mobs/Species/kidan.yml

Спрятаны уши и рога киданов и вульпканинов в скафандрах
:cl:
- fix: Спрятаны рога и уши вульпканинов и киданов в скафандрах

Hide ears and horns of kidans and vulpkanins

---

Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml

Добавлено слабое красное свечение Голиафу.
Часты случаи, когда утилизатор даже не видит Голиафа, условно, копает руду и тут из-под земли появляются тентакли и кидают игрока в стамина-крит. Слабое свечение по крайней мере предупредит игрока.
:cl:
- tweak: Добавлено слабое красное свечение Голиафам

Add weak red light to goliath

---

Content.Shared/Standing/StandingStateSystem.cs

Теперь звуки хотьбы появились обратно
:cl:
- fix: Пофикшено отсутствие звуков хотьбы

Fix footstep sound

---

Content.Server/_Exodus/Administration/UI/Audio/AdminAudioPanelEui.cs

Исправление валидации пути к трекам в админской аудио панели. Ранее, валидация была сделана не совсем верно, из-за чего проходили её только треки из Uploaded. Теперь она пофикшена.

Fix Admin Audio Panel tracks validation

---

.github/workflows/publish-artifact.yml
.github/workflows/publish.yml

Порезаны версии, под которые собирается сервер при упаковке через Github Workflow, а именно OSX 64 и LinuxARM64. Я просто не хочу так долго ждать, а эти версии никак не используются.

Wait a little bit less for private packaging

---

Resources/Prototypes/Voice/disease_emotes.yml
Resources/Prototypes/_Exodus/Entities/Mobs/Species/felinid.yml

Исправлен баг c наличием эмоции шипения у всех рас.
:cl:
- fix: Исправлен баг c наличием эмоции шипения у всех рас.

Hisses fix

---

Content.Server/NPC/HTN/Preconditions/TargetInLOSPrecondition.cs
Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs
Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs

Улучшение логики турелей!
- Турели теперь попадают по лежащим
- Турели больше не стреляют по врагу, если на пути огня стоит существо дружественной ей фракции. Если существо не враг, но и не друг, то оно будет проигнорировано и огонь всё-равно будет открыт (прикрываться животными от турелей не выйдет).
https://github.com/user-attachments/assets/61a270a7-4192-47b6-89d6-e99e7c64f7d6
:cl:
- tweak: Турели больше не стреляют по врагу, если на пути огня стоит существо дружественной ей фракции (животных игнорирует)
- fix: Турели теперь попадают по лежачим

Improve turrets logic

---

Resources/Prototypes/_Exodus/Entities/Mobs/Species/kidan.yml

У киданов теперь кровь инсектоидов
Лор
<!--
:cl:
- tweak: Кровь киданов изменена на кровь инсектоидов

Insect blood for kidans

---

Content.Client/_Exodus/Mining/MiningScannerViewerSystem.cs
Content.Server/Flash/FlashSystem.cs
Content.Server/Nutrition/EntitySystems/FoodSystem.cs
Content.Server/_Exodus/Mining/MiningScannerSystem.cs
Content.Server/_Exodus/Mining/MiningScannerViewerSystem.cs
Content.Server/_Exodus/Traits/Species/MineralResonance/MineralResonanceSystem.cs
Content.Shared/Flash/SharedFlashSystem.cs
Content.Shared/_Exodus/Mining/Components/MiningScannerComponent.cs
Content.Shared/_Exodus/Mining/Components/MiningScannerUserComponent.cs
Content.Shared/_Exodus/Mining/Components/MiningScannerViewable.cs
Content.Shared/_Exodus/Mining/Components/MiningScannerViewerComponent.cs
Content.Shared/_Exodus/Mining/SharedMiningScannerSystem.cs
Content.Shared/_Exodus/Mining/SharedMiningScannerViewerSystem.cs
Content.Shared/_Exodus/Traits/Species/SensitiveEyes/SensitiveEyesComponent.cs
Resources/Prototypes/_Exodus/Entities/Mobs/Species/new_kidan.yml
Resources/Prototypes/_Exodus/Voice/speech_emotes.yml

Исправление кидан:
- Исправление минерального резонанса
- Исправление работы вспышек
- Исправление работы эмоций кидан
- Исправление шахтёрского сканера
*No Media*
*No CL*

fix(upstream): fix kidan mineral resonance amd etc

---

Resources/Prototypes/Corvax/Entities/Mobs/Player/tajaran.yml
Resources/Prototypes/Corvax/Entities/Mobs/Species/tajaran.yml
Resources/Prototypes/Corvax/Species/tajaran.yml
Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
Resources/Prototypes/_Exodus/Entities/Mobs/Player/humanoid.yml

Более полное удаление таяр, дабы они не появлялись на случайных спавнерах.
:cl:
- remove: Более полное удаление таяр, дабы они не появлялись на случайных спавнерах.

(upstream) Tatari... Ooops, Tajaran delete

---

.github/workflows/build-map-renderer.yml
.github/workflows/build-test-debug.yml
.github/workflows/test-packaging.yml
.github/workflows/validate-rgas.yml
.github/workflows/validate-rsis.yml
.github/workflows/validate_mapfiles.yml
.github/workflows/yaml-linter.yml

Апстримы являются частью жизненного цикла нашей сборки, потому тесты для них тоже должны запускаться

Make tests run for upstream branch

---

Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
Resources/Prototypes/Corvax/Roles/Jobs/Security/pilot.yml
Resources/Prototypes/Roles/Antags/ninja.yml
Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/departments.yml
Resources/Prototypes/_Exodus/Roles/Jobs/CentCom/blueshield_officer.yml
Resources/Prototypes/_Exodus/Roles/Jobs/CentCom/death_squad.yml
Resources/Prototypes/_Exodus/Roles/Jobs/Security/brigmedic.yml

Изменены/убраны/добавдены новые виды наборов для хамелеона.
:cl:
- add: Добавлены наборы хамелеона для бригмедика, АВД, пилота, ЭС (Эксодуса), ОСЩ.
- remove: Удалены наборы хамелеона ниндзя и ЭС (оффовский).
- tweak: Изменены наборы хамелеона для ГСБ и ЛОБРа.

Better chameleon

---

Resources/Prototypes/Corvax/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/Entities/Clothing/Back/satchel.yml
Resources/Prototypes/_Exodus/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/_Exodus/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/_Exodus/Entities/Clothing/Back/satchel.yml

Добавлен резист ко взрыву некоторым сумкам По решению в https://github.com/space-exodus/QA/issues/8.
:cl:
- add: Добавлен резист ко взрыву некоторым сумкам

ExplosionResistance Add

---

Content.Server/Administration/Systems/AdminVerbSystem.Smites.cs
Content.Server/_Exodus/Speech/Components/BurrinessAccentComponent.cs
Content.Server/_Exodus/Speech/EntitySystems/BurrinessAccentSystem.cs
Resources/Locale/ru-RU/exodus/traits/traits.ftl
Resources/Prototypes/Entities/Mobs/Player/clone.yml
Resources/Prototypes/_Exodus/Traits/speech.yml

Добавление нового акцента - картавости. Заменяет все буквы Р на В. Также добавлены акценты эксодуса в омниакценты и копирование клонами
:cl:
- add: Добавлен новый акцент- Картавость.
- tweak: Картавость и акцент киданов добавлен в омниакцент (наказание от админов).
- tweak:  Картавость и акцент киданов добавлен в список копирования компонентов у клонов.

Burriness Accent
